version: '3.4'

services:
  api:
    image: api
    container_name: api
    build:
      context: api
      dockerfile: ./Dockerfile.debug
    ports:
      - "8000:8000"
      - "5678:5678"
    command: sh -c "python manage.py makemigrations && pip install debugpy==1.3.0 -t /tmp && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./api:/app
  web:
    image: web
    container_name: web
    build:
      context: web
      dockerfile: ./Dockerfile.debug
    environment:
      NODE_ENV: development
    ports:
      - 80:80
      - 9229:9229
    volumes:
      - "./web:/app"
      - "/app/node_modules"
    command: yarn --cwd web start